[toolchain]
anchor = "0.30"

[provider]
cluster = "testnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run anchor test"

[profile.release]
overflow-checks = true
lto = true
codegen-units = 1
